name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "5.15.12"
  VERSION: 0.9
  LONG_VERSION: 0.9.9
  CURRENT_YEAR: 2023
  FILE_BASENAME: DWDWeatherDataConverter_Win
  INNOSETUP_VERSION: "6.2.0"


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create Directory
      run: mkdir bin\release_x64
      shell: cmd
    
    - name: Download and Install Inno Setup
      run: |
        $url = "files.jrsoftware.org/is/6/innosetup-6.2.0.exe"
        $output = "${{github.workspace}}\innosetup-6.2.0-unicode.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process $output -ArgumentList "/VERYSILENT" -NoNewWindow -Wait
        
    - name: Prepare Inno Setup Script
      run: |
        # Replace placeholders in .iss.in file here. 
        # This is just an example, adjust it to your needs.
        (Get-Content ${{github.workspace}}\build\installer\deploy64.iss.in) `
        | Set-Content ${{github.workspace}}\build\installer\deploy64.iss
      shell: powershell
    
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
          toolset: 16.11

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
    
        
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      working-directory: ${{github.workspace}}\build\cmake
      run: cmake ${{github.workspace}}\build\cmake -G "NMake Makefiles JOM" .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}\build\cmake
      run: jom

    - name: Test
      working-directory: ${{github.workspace}}\build\cmake
      run: ctest -C ${{env.BUILD_TYPE}} 
      
    - name: Copy Executable
      run: |
        "xcopy /Y ${{github.workspace}}\build\cmake\DWDWeatherDataConverter\release\DWDWeatherDataConverter.exe ${{github.workspace}}\bin\release_x64"
      shell: cmd

    - name: Build Installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "${{github.workspace}}\build\installer\deploy64.iss"
      shell: cmd

