name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  VERSION: 0.9.9
  QT_VERSION: "5.15.12"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      working-directory: ${{github.workspace}}\build\cmake
      run: cmake ${{github.workspace}}\build\cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --debug-output

    - name: Build
      working-directory: ${{github.workspace}}\build\cmake
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}\build\cmake
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Prepare Inno Setup Script
      run: |
        # Replace placeholders in .iss.in file here. 
        # This is just an example, adjust it to your needs.
        (Get-Content DWD-Weather-Data-Converter/build/installer/deploy64.iss.in) `
        -replace 'app', 'DWDWeatherDataConverter' `
        -replace 'version', '${{env.VERSION}}' `
        | Set-Content ${{github.workspace}}/build/installer/deploy64.iss
      shell: powershell
      
    - name: Download and Install Inno Setup
      run: |
        $url = "http://files.jrsoftware.org/is/$env:INNOSETUP_VERSION/innosetup-$env:INNOSETUP_VERSION-unicode.exe"
        $output = "${{github.workspace}}\innosetup-$env:INNOSETUP_VERSION-unicode.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process $output -ArgumentList "/VERYSILENT" -NoNewWindow -Wait

    - name: Build Installer
      run: |
        "$env:ProgramFiles(x86)\Inno Setup 6\ISCC.exe" "${{github.workspace}}/build/installer/deploy64.iss"
      shell: powershell

