name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "5.15.2"
  VERSION: "1.0"
  LONG_VERSION: "1.0.0"
  CURRENT_YEAR: "2023"
  FILE_BASENAME: "DWDWeatherDataConverter_Win64"
  INNOSETUP_VERSION: "6.2.0"

jobs:
  build:
    runs-on: windows-latest
     
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d')"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: echo "Building..."
    - name: Show current date
      run: echo "The current date is ${{ steps.date.outputs.date }}"

    - uses: actions/checkout@v3
    
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: hirseboy/installer-scripts
        token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT
        path: ${{github.workspace}}\installer-scripts       
    
    - name: Create Directory
      run: mkdir ${{github.workspace}}\bin\release_x64
      shell: cmd
      
    - name: Create Directory
      run: mkdir ${{github.workspace}}\build\installer
      shell: cmd
      
    - name: Print iss.in
      run: type ${{github.workspace}}\installer-scripts\DWDWeatherDataConverter\deploy64.iss.in
      shell: cmd
    
    - name: Prepare Inno Setup Script
      run: |
        # Replace placeholders in .iss.in file. 
        xcopy /E ${{github.workspace}}\installer-scripts\DWDWeatherDataConverter\ ${{github.workspace}}\build\installer\
        $content = Get-Content ${{github.workspace}}\build\installer\deploy64.iss.in 
        $content = $content -replace "\$\{Version\}", "${{env.VERSION}}"
        $content = $content -replace "\$\{LongVersion\}", "${{env.LONG_VERSION}}" 
        $content = $content -replace "\$\{CurrentYear\}", "${{env.CURRENT_YEAR}}" 
        $content = $content -replace "\$\{OutputFileBasename\}", "${{env.FILE_BASENAME}}"
        $content | Set-Content ${{github.workspace}}\build\installer\deploy64.iss
      shell: powershell

    - name: Print iss
      run: type ${{github.workspace}}\build\installer\deploy64.iss
      shell: cmd
    
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vs-version: 16  # Visual Studio 2019 corresponds to version 16

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: ${{env.QT_VERSION}}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        cache: true
        
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      working-directory: ${{github.workspace}}\build\cmake
      run: cmake ${{github.workspace}}\build\cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      working-directory: ${{github.workspace}}\build\cmake
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}\build\cmake
      run: ctest -C ${{env.BUILD_TYPE}} 
      
    - name: Print files
      run: tree /f ${{github.workspace}}
      shell: cmd
      
    - name: Copy Executable
      run: |
        xcopy /Y ${{github.workspace}}\build\cmake\DWDWeatherDataConverter\release\DWDWeatherDataConverter.exe ${{github.workspace}}\bin\release_x64
        xcopy /Y ${{github.workspace}}\DWDWeatherDataConverter\resources\translations\DWDWeatherDataConverter_de.qm ${{github.workspace}}\bin\release_x64
      shell: cmd

    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "${{github.workspace}}\build\installer\deploy64.iss"
      shell: cmd
      
    - name: Print files
      run: tree /f ${{github.workspace}}
      shell: cmd

    - name: Upload Installer as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "${{env.FILE_BASENAME}}_${{ steps.date.outputs.date }}"
        path: ${{github.workspace}}\build\installer\DWDWeatherDataConverter_win64.exe # Ersetzen Sie dies durch den Pfad zu Ihrer Installer-Datei
    
    - name: Rename installer
      run: move "${{github.workspace}}\build\installer\DWDWeatherDataConverter_win64.exe" "${{github.workspace}}\build\installer\${{ steps.date.outputs.date }}_DWDWeatherDataConverter_win64.exe"
      shell: cmd
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GH_RELEASE }}
        file: ${{github.workspace}}\build\installer\${{ steps.date.outputs.date }}_DWDWeatherDataConverter_win64.exe
        tag: nightly
        overwrite: true
        body: "Nightly Release of DWD Weather Data Converter from ${{ steps.date.outputs.date }}"


